---
title: "R Tidy"
output:
  github_document:
    toc: true
    html_preview: true
---

```{r, message=FALSE}
# Visualization
library(knitr) 

library(tidyr) # spread, gather
library(dplyr) # mutate, ...

set.seed(0)
```
  
## Baseline/Follow-up ratio
For each sample and variable we want to compute the baseline-follow-up ratio.
BA: Baseline, FO: Follow-up, 3 variables.

```{r}
df = data.frame(Subject=rep(c("S1","S2","S3"), each=2),
                Measure=rep(c("BA","FO"), 3),
                Var1=rnorm(6), Var2=rnorm(6), Var3=rnorm(6))

kable(df)
```

```{r}
df_ratio = df %>% 
  gather(Var, Value, Var1:Var3) %>%
  group_by(Subject, Var) %>%
  spread(Measure, Value) %>%
  mutate(Ratio=BA/FO)

kable(df_ratio)
```

## Spread multiple columns

```{r}
df = data.frame(Subject=rep(c("S1","S2","S3"), each=2),
                Group=rep(c("G1", "G2"), 3),
                Var1=rnorm(6), Var2=rnorm(6), Var3=rnorm(6))
kable(df)
```

```{r}
df_spread = df %>% 
  gather(variable, value, -(Subject:Group)) %>%
  unite(temp, Group, variable, sep=".") %>%
  spread(temp, value)

kable(df_spread)
```

## Transpose
```{r}
df = data.frame(Subject=c("S1","S2","S3", "S4"),
                Var1=rnorm(4), Var2=rnorm(4), Var3=rnorm(4))

kable(df)
```
```{r}
df_t = df %>% 
  gather(Var, Val, -Subject) %>% 
  spread(Subject, Val)

kable(df_t)
```

## Move a column to the first position

```{r}
df = data.frame(Var1=rnorm(4),  Var2=rnorm(4), Var3=rnorm(4))

kable(df)
```
```{r}
df_m = df %>% 
  select(Var2, everything())

kable(df_m)
```


